### ISSUE TITLE
Open to contributions?

### ISSUE THREAD

**Issue by Fdawgs** [maxlath/fix-utf8#2]
Hi @maxlath, is this repo open to contributions?
If so, would you be happy for me to make a few PRs to update the dev dependencies and add GitHub Actions CI?

**Comment by maxlath** [comment]
Sure! What do you have in mind for the GitHub Actions?

**Comment by maxlath** [comment]
Both PRs have been merged and published in v1.1.2

**Comment by Fdawgs** [comment]
Thank you!
