### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by Fdawgs** [maxlath/fix-utf8#5]
TypeScript cries wolf because this module does not have any types included, is it possible for these to be added?

Happy to have a go at adding them myself with a PR, however TS is not my area at all!

**Comment by maxlath** [comment]
I added type annotations with JSDoc and used it to generate a `index.d.ts` types declaration file, published in `v1.2.1`; can you check if that satisfies your needs?

**Comment by Fdawgs** [comment]
Brilliant, thanks @maxlath, works a treat!
